sudo: required
services:
  - docker

before_install:
  - docker build -t maxoud/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maxoud/react-test npm test -- --coverage

after_success:
  - docker build -t maxoud/multi-client ./client
  - docker build -t maxoud/multi-nginx ./nginx
  - docker build -t maxoud/multi-server ./server
  - docker build -t maxoud/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push maxoud/multi-client
  - docker push maxoud/multi-nginx
  - docker push maxoud/multi-server
  - docker push maxoud/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-east-2-
